In [2]:
import numpy as np #list conver into array


In [3]:
arr1=[12,23,5,]
print(arr1)

[12, 23, 5]


In [4]:
arr5=list(range(1,10))



In [5]:
print(type(arr5))

<class 'list'>


In [2]:
a=5,because bydefalt tuple hi leta h is ki 
type(a)

tuple

In [3]:
import numpy as np
print ('harsh')

harsh


In [4]:
harsh=np.array(lst)
print(harsh)
print(type(harsh))
print(type(lst))

NameError: name 'lst' is not defined

In [6]:
arr2=list(range(1,2))
print((type(arr2)))
arr2=list(range(1,10)) 
arr2 =np.array(arr2)
arr2
print(type(arr2))

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
arr4=np.array([1,2,2,5,9])
arr4

array([1, 2, 2, 5, 9])

In [12]:
arr5=np.zeros((5,20))
arr5

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [13]:
np.ones((10,5)) 
# 10= show that row
# 5= show that column

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.linspace(1,10,5)yha 5 btata h ki 1 se 10ke bich ,me 5 tukde(variable)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [16]:
np.arange(0,30).reshape(10,3)
# reshape=with help 1d convert to 2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [17]:
np.random.randint(1,5,(5,1))

array([[4],
       [1],
       [1],
       [1],
       [1]], dtype=int32)

# random number 

In [22]:
a=np.arange(60).reshape(2,30)
a.shape
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
# n=number
# dim=dimantion
# np.ndim dimantion btane ke liye 


In [26]:
# ravel ki help se 2d ko 1d me convert karteh
a= np.arange(60)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [27]:
a[10] 

np.int64(10)

In [32]:
arr=np.arange(60).reshape(12,5)
arr
arr[11:12,4:5]

array([[59]])

In [34]:
a=[5:6,2:3]

SyntaxError: invalid syntax (3067168019.py, line 1)

In [36]:
arr[7:8,4:5]

array([[39]])

In [38]:
arr[11:12;4:5]

SyntaxError: invalid syntax (4043872723.py, line 1)

In [39]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [40]:
arr[7:8,3:5]

array([[38, 39]])

In [44]:
arr
arr[11][-1]
arr[-1][-1]
arr[-1,-1]

np.int64(59)

3d

In [50]:
arr5=np.arange(225).reshape(5,15,3)

In [57]:
arr5 [4]
arr5[-1,-1]

array([222, 223, 224])

In [59]:
arr5
arr[1][5:3]

array([], dtype=int64)

In [ ]:
9